[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
